### ISSUE TITLE
Build on OSX Catalina?

### ISSUE THREAD

**Issue by brandon-zeeb-nw** [ComposersDesktop/CDP7#3]
Hello!

It seems the cmake build is missing a few things for the Apple platform, the `AAIOLIB` is not set for `APPLE`, `io.h` and `winsock.h` are tested on Apple and they don't exist.  After those are fixed, the build complains about missing source files.

Have you had a moment to get the build operational in OSX Catalina? 

My main goal in asking is to have x86_64 binaries produced for Catalina, the binaries I've found online for Mac don't work on Catalina.

Thanks!

**Comment by brandon-zeeb-nw** [comment]
Will post a PR for this soon.

**Comment by phasebash** [comment]
Fixed in #4
