### ISSUE TITLE
Build fails on Linux

### ISSUE THREAD

**Issue by musger** [ComposersDesktop/CDP7#5]
Running cmake the following way
`mkdir build
cd build
cmake ..`
fails as AAIOLIB needs to be set and the file cmake/CompilerOptimizations.cmake is not found. With 
`cmake -DAAIOLIB=/usr/local/lib/libaaio.a -DUSE_COMPILER_OPTIMIZATIONS=no`
this run succeeds.

Running make as a next step fails with
`[  4%] Building C object dev/sfsys/CMakeFiles/sfsys.dir/sfdir.c.o`
`/home/user/devel/cdp/git/CDP7/dev/sfsys/sfdir.c: In function ‘sfdir’:`
`/home/user/devel/cdp/git/CDP7/dev/sfsys/sfdir.c:148:13: error: ‘strncpy’ output may be truncated copying 63 bytes from a string of length 255 [-Werror=stringop-truncation]`
`  148 |             strncpy(dir.name, f->d_name, MAXSFNAME);`
`/home/user/devel/cdp/git/CDP7/dev/sfsys/sfdir.c:118:13: error: ‘strncpy’ output may be truncated copying 63 bytes from a string of length 255 [-Werror=stringop-truncation]`
`  118 |             strncpy(dir.name, f->d_name, MAXSFNAME);`
`cc1: all warnings being treated as errors`
`make[2]: *** [dev/sfsys/CMakeFiles/sfsys.dir/build.make:89: dev/sfsys/CMakeFiles/sfsys.dir/sfdir.c.o] Error 1`
`make[1]: *** [CMakeFiles/Makefile2:1432: dev/sfsys/CMakeFiles/sfsys.dir/all] Error 2`
`make: *** [Makefile:152: all] Error 2`

**Comment by jpffitch** [comment]
This is a longstanding potential bug that was ignored until now.  You can 
restore previous behaviour by removing the -Werror flag from 
CMakeLists.txt

Will look at a real fix.

**Comment by musger** [comment]
Awesome! It builds! There were multiple warnings on the way though, let me know if you would like to know about them. All this should go into linux build instructions, which I could write up as well. Thanks!

**Comment by jpffitch** [comment]
Mew version committed

**Comment by musger** [comment]
Is this commit about the error message above? In this case for the new version the error message changes slightly to
`sfdir.c:148:13: error: ‘strncpy’ output may be truncated copying 255 bytes from a string of length 255 [-Werror=stringop-truncation]`
`sfdir.c:118:13: error: ‘strncpy’ output may be truncated copying 255 bytes from a string of length 255 [-Werror=stringop-truncation]`
